🗃️ Committing everything that changed 🗃️

diff --git a/rootfs/usr/local/bin/buildx b/rootfs/usr/local/bin/buildx
--- a/rootfs/usr/local/bin/buildx
+++ b/rootfs/usr/local/bin/buildx
@@ -29,13 +29,11 @@ __buildx() {
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Initialize
   echo "Setting target platform to $platforms"
-  echo "Setting the buildername to $buildername"
-  echo "Initializing $qemu_imagename $binfmt_imagename"
-  __image_exists "$qemu_imagename" || docker run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes &>/dev/null || { echo "Failed to Initialize" && exit 1; }
-  __image_exists "$binfmt_imagename" || docker run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all &>/dev/null || { echo "Failed to Initialize" && exit 1; }
-  __image_exists "$buildername" || docker buildx create --name "$buildername" --use &>/dev/null || { echo "Failed to Initialize" && exit 1; }
-  docker buildx use "$buildername" &>/dev/null || { echo "Failed to Initialize" && exit 1; }
-  docker buildx inspect --bootstrap &>/dev/null || { echo "Failed to Initialize" && exit 1; }
+  __image_exists "$qemu_imagename" || { echo "Initializing $qemu_imagename" && docker run -d --name "$qemu_imagename" --privileged multiarch/qemu-user-static --reset -p yes &>/dev/null; } #|| { echo "Failed to Initialize" && exit 1; }
+  __image_exists "$binfmt_imagename" || { echo "Initializing $binfmt_imagename" && docker run -d --name "$binfmt_imagename" --privileged tonistiigi/binfmt --install all &>/dev/null; }     #|| { echo "Failed to Initialize" && exit 1; }
+  __image_exists "$buildername" || { echo "Setting the buildername to $buildername" && docker buildx create --name "$buildername" --use &>/dev/null; }                                      #|| { echo "Failed to Initialize" && exit 1; }
+  docker buildx use "$buildername" &>/dev/null                                                                                                                                              #|| { echo "Failed to Initialize" && exit 1; }
+  docker buildx inspect --bootstrap &>/dev/null                                                                                                                                             #|| { echo "Failed to Initialize" && exit 1; }
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   # Build
   echo "Building $reg_tag"
@@ -76,11 +74,16 @@ docker_files="$(find "/root/build" -name 'Dockerfile*' 2>/dev/null | sort -u | g
 export DOCKER_CLI_EXPERIMENTAL="enabled"
 echo "$TAG_NAME" | grep -q ':' || TAG_NAME="$TAG_NAME:latest"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-[ -n "$(pgrep -x dockerd)" ] || start-docker.sh &>/dev/null &
 [ -n "$docker_file" ] || [ -n "$docker_files" ] || { echo "USAGE: buildx [dir] [tagname]" && exit 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main application
 clear
+if [ -z "$(pgrep -x dockerd)" ]; then
+  echo "Starting dockerd"
+  start-docker.sh &>/dev/null &
+  sleep 10
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main application
 if [ -n "$docker_file" ]; then
   [ -n "$TAG_NAME" ] || { echo "USAGE: buildx [dir] [tagname]" && exit 1; }
   directory="$(dirname "$docker_file")"
